databases:
  - name: ecolearn-db
    plan: free
    databaseName: eco_learning_db
    user: ecolearn_user

services:
  # Spring Boot Web API
  - type: web
    name: ecolearn-api
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/Vijayanand0842/Ecolearn-Backend.git
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: ecolearn-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ecolearn-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: ecolearn-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ecolearn-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ecolearn-db
          property: password
