services:
  # Spring Boot Web API (Dockerized)
  - type: web
    name: ecolearn-api
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/Vijayanand0842/Ecolearn-Backend.git
    envVars:
      # These will be provided by the user in Render Dashboard,
      # or they can paste the Railway MySQL URL here.
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
