# Server config (Vite proxy points to 5000)
server.port=${PORT:5000}

# MySQL config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/eco_learning_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Vijayanand2005@}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true

# SMTP Mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vijaygrd0803@gmail.com
spring.mail.password=ioag qpvn yoce vbdl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
